name: Build and Commit
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:  # Environment variables from either organization or repository settings page (for GitHub Actions).
      TENOR_KEY: ${{ secrets.TENOR_KEY }}
      SPHERON_BUCKET_NAME: ${{ secrets.SPHERON_BUCKET_NAME }}
      SPHERON_STORAGE_TOKEN: ${{ secrets.SPHERON_STORAGE_TOKEN }}
      IMAGEKIT_ENDPOINT: ${{ secrets.IMAGEKIT_ENDPOINT }}
      IMAGEKIT_PUBLIC_KEY: ${{ secrets.IMAGEKIT_PUBLIC_KEY }}
      IMAGEKIT_PRIVATE_KEY: ${{ secrets.IMAGEKIT_PRIVATE_KEY }}
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2.3.1

      - name: Install and Build üîß # This example project is built using npm and outputs the result to the 'build' folder.
        run: |
          npm install
          npm run generate
      - name: Deploy üöÄ
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: build # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.